# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('salary', models.IntegerField(default=250000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('log', models.DateTimeField(auto_now=True)),
                ('Attributes', models.CharField(default='Haemoglobin, WBC', max_length=500)),
                ('numattr', models.IntegerField(default=10)),
                ('Classification_Status', models.CharField(default='Yes', max_length=5)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.Doctor')),
            ],
        ),
    ]
